
import React, { useState, useEffect } from 'react';
import { Shield, X } from 'lucide-react';
import CTAButton from './CTAButton';

interface ConsentModalProps {
  onAccept: () => void;
}

const ConsentModal: React.FC<ConsentModalProps> = ({ onAccept }) => {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    // Small delay for animation effect
    const timer = setTimeout(() => {
      setIsVisible(true);
    }, 1000);

    return () => clearTimeout(timer);
  }, []);

  if (!isVisible) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center px-4 backdrop-blur-md bg-cyber-black/50">
      <div className="glass-morphism bg-cyber-darker/90 rounded-xl p-6 max-w-lg w-full border border-cyber-blue/30 shadow-neon-blue animate-fade-in">
        <div className="flex justify-between items-start mb-4">
          <div className="flex items-center">
            <Shield className="text-cyber-blue w-6 h-6 mr-2" />
            <h3 className="text-xl font-display font-bold text-white">Consent Required</h3>
          </div>
          <button 
            onClick={onAccept} 
            className="text-white/60 hover:text-white"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        
        <div className="text-white/80 space-y-4 mb-6">
          <p>
            By using Grant Writer GPT, you acknowledge and agree to the following:
          </p>
          
          <ul className="list-disc pl-5 space-y-2">
            <li>
              This AI tool provides assistance in drafting grant proposals but does not guarantee funding success.
            </li>
            <li>
              You are responsible for reviewing and verifying all content generated by the tool before submission.
            </li>
            <li>
              Your interactions with Grant Writer GPT are subject to OpenAI's privacy policy and terms of service.
            </li>
            <li>
              AI WEB TOOLS LLC provides this as a tool only and is not offering professional grant writing services or legal advice.
            </li>
          </ul>
          
          <p>
            For complete details, please review our full disclaimer and terms of service.
          </p>
        </div>
        
        <div className="flex justify-center">
          <CTAButton onClick={onAccept} size="lg">
            I Agree
          </CTAButton>
        </div>
      </div>
    </div>
  );
};

export default ConsentModal;
